apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}-agent
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
spec:
  ports:
    - port: {{ .Values.master.slaveListenerPort }}
      targetPort: {{ .Values.master.slaveListenerPort }}
      name: slavelistener
  selector:
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.master.slaveListenerServiceType }}