apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins.serviceAccountAgentName" . }}
  namespace: {{ template "jenkins.master.kubernetesNamespace" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
