apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-post-install
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  post-install-script.sh:  |-
    cp /var/install_scripts/plugins.txt /var/jenkins_home;
    /usr/local/bin/install-plugins.sh < /var/jenkins_home/plugins.txt;
    yes n | cp -i /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins/;
    {{- if .Values.master.jobs.enabled }}
    for filename in /var/jenkins_jobs/*.xml; do
      name=$(basename "$filename" ".xml")
      mkdir -p /var/jenkins_home/jobs/$name
      cp -i $filename /var/jenkins_home/jobs/$name/config.xml
    done
    {{- end }}
  plugins.txt: |-
    kubernetes:1.18.2
    workflow-job:2.33
    workflow-aggregator:2.6
    credentials-binding:1.19
    git:3.11.0
    configuration-as-code:1.27
    nodejs:1.3.3
    docker-workflow:1.19
