apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
spec:
  ports:
    - port: {{ .Values.master.servicePort }}
      name: http
      targetPort: {{ .Values.master.targetPort }}
      {{- if .Values.master.nodePort }}
      nodePort: {{.Values.master.nodePort.port}}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: "NodePort"